initial implementation of color as state
togglebyte/anathema pull request #62
Opened 2024-09-05 16:05 UTC by wllfaria

2024-09-07 15:41 UTC, FishingHacks requested changes

2024-09-07 15:41 UTC, FishingHacks commented on anathema-backend/src/tui/style.rs
> +            "background" => self.fg,
i believe that `background => self.fg` is incorrect

```suggestion
            "background" => self.bg,
```

2024-09-07 15:41 UTC, FishingHacks commented on anathema-state/src/colors.rs
> +    /// See [256 colorts](https://en.wikipedia.org/wiki/ANSI_escape_code#8-bit)
```suggestion
    /// See [256 colors](https://en.wikipedia.org/wiki/ANSI_escape_code#8-bit)
```

2024-09-07 15:41 UTC, FishingHacks commented on anathema-state/src/colors.rs
> +        Hex::try_from(value).map(Into::into)
Shouldn't this use the FromStr trait as defined below?

2024-09-07 15:41 UTC, FishingHacks commented on anathema-widgets/src/widget/attributes.rs
> +            CommonVal::Color(color) => Some(color),
```suggestion
            CommonVal::Color(color) => Some(color),
            CommonVal::Str(str) => Color::from_str(str).ok(),
            CommonVal::Int(ansi_value @ 0..=u8::MAX as i64) => Some(Color::AnsiVal(ansi_value as u8)),
```

The string case is handled by the TUI. I would suggest moving it down here with the code above. This way, lines 143-152 of `anathema-backend/src/tui/style.rs` can be simplified.

2024-09-08 13:22 UTC, togglebyte approved these changes

2024-09-08 13:22 UTC, merged